### ISSUE TITLE
Store date on Orders, separate from Seatings

### ISSUE THREAD

**Issue by ToddPeterson** [ToddPeterson/bobs_eatery#4]
Orders don't necessarily have a seating (ie. online orders), so maybe we should store a date on the order itself.

**Comment by DrewTChrist** [comment]
On top of this the dates that we populate the database with need to have some variety. The way they're currently populated means that every order out of the 100 occurred on the same day so that will make querying a little strange.

https://github.com/ToddPeterson/bobs_eatery/blob/1f17996a424fa8326cf5d2727a299859b41bee6c/deliverables/04/populate_db1.sql#L190

**Comment by DrewTChrist** [comment]
https://github.com/ToddPeterson/bobs_eatery/commit/0f82682047eb395700388519ded641a5e7da0a5c
